using System.Security.Claims;
using GymSaaS.Application.Common.Interfaces;
using GymSaaS.Domain.Enums;
using GymSaaS.Domain.Interfaces;
using Microsoft.AspNetCore.Http;

namespace GymSaaS.Infrastructure.Identity;

public class TenantResolver : ITenantResolver, ICurrentUserService
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public TenantResolver(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public string? UserId => _httpContextAccessor.HttpContext?.User.FindFirstValue(ClaimTypes.NameIdentifier);

    public string? ActorId => UserId;

    public ActorType? ActorType
    {
        get
        {
            var val = _httpContextAccessor.HttpContext?.User.FindFirstValue("actor_type") ??
                      _httpContextAccessor.HttpContext?.User.FindFirstValue(ClaimTypes.Role);
            return Enum.TryParse<ActorType>(val, true, out var result) ? result : null;
        }
    }

    public int? FacilityId
    {
        get
        {
            var val = _httpContextAccessor.HttpContext?.User.FindFirstValue("facility_id");
            return int.TryParse(val, out int id) ? id : null;
        }
    }

    public int? BranchId
    {
        get
        {
            var val = _httpContextAccessor.HttpContext?.User.FindFirstValue("branch_id");
            return int.TryParse(val, out int id) ? id : null;
        }
    }

    /// <summary>
    /// True only when the caller is the supervisor operating with their own primary token —
    /// NOT during an impersonation session (which is scoped to a single facility).
    /// </summary>
    public bool IsSupervisor
    {
        get
        {
            // An impersonation token belongs to a supervisor but must be treated
            // as a tenant-scoped session, not a global supervisor session.
            if (IsImpersonating) return false;

            var actorTypeClaim = _httpContextAccessor.HttpContext?.User.FindFirstValue("actor_type");
            return actorTypeClaim == "Supervisor" || actorTypeClaim == "SUPERVISOR";
        }
    }

    /// <summary>
    /// True when the current token is an impersonation token generated by
    /// <see cref="ImpersonationTokenService"/>. Impersonation tokens always carry
    /// the «on_behalf_of_role» claim and the «is_impersonating» flag.
    /// </summary>
    public bool IsImpersonating
    {
        get
        {
            var impersonatingFlag = _httpContextAccessor.HttpContext?.User.FindFirstValue("is_impersonating");
            var onBehalfOfRole = _httpContextAccessor.HttpContext?.User.FindFirstValue("on_behalf_of_role");
            return impersonatingFlag == "true" || !string.IsNullOrEmpty(onBehalfOfRole);
        }
    }

    public string? OnBehalfOfRole => _httpContextAccessor.HttpContext?.User.FindFirstValue("on_behalf_of_role");
}
